"""Add cover image field to article

Revision ID: 19a8ade9b537
Revises: ff426c9fb4aa
Create Date: 2025-02-27 23:24:05.099584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a8ade9b537'
down_revision = 'ff426c9fb4aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('cover_image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'cover_image')
    # ### end Alembic commands ###
