"""add user fields

Revision ID: 1cdcb12f69e0
Revises: fd470c3ddd8a
Create Date: 2024-11-25 23:12:30.120863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cdcb12f69e0'
down_revision = 'fd470c3ddd8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_address', sa.String(), nullable=False))
    op.add_column('users', sa.Column('interests', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'location')
    op.drop_column('users', 'interests')
    op.drop_column('users', 'email_address')
    # ### end Alembic commands ###
