"""add file name to entities

Revision ID: 3f4b64f53c49
Revises: 1cdcb12f69e0
Create Date: 2024-11-25 23:29:00.458160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4b64f53c49'
down_revision = '1cdcb12f69e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'file_name')
    # ### end Alembic commands ###
