"""Add cascade delete for article/quiz/quizcompletions

Revision ID: a11070c62f1b
Revises: caf14c94bfaf
Create Date: 2025-03-21 20:44:01.687759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a11070c62f1b'
down_revision = 'caf14c94bfaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('test', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'test')
    # ### end Alembic commands ###
