"""add subtitle

Revision ID: a1bb5c214a3b
Revises: bb4486427f92
Create Date: 2025-02-28 03:27:59.916063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1bb5c214a3b'
down_revision = 'bb4486427f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('subtitle', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'subtitle')
    # ### end Alembic commands ###
