"""Add filename field to entity

Revision ID: b16735932d51
Revises: 19a8ade9b537
Create Date: 2025-02-03 20:45:19.394136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16735932d51'
down_revision = '19a8ade9b537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'file_name')
    # ### end Alembic commands ###
