"""add fields to article

Revision ID: b71e557e50fe
Revises: a1bb5c214a3b
Create Date: 2025-03-14 22:45:42.503463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71e557e50fe'
down_revision = 'a1bb5c214a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('number_of_ratings', sa.Integer(), nullable=True))
    op.add_column('article', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('article', sa.Column('time_to_read', sa.Integer(), nullable=True))
    op.drop_column('article', 'comments_count')
    op.drop_column('article', 'views_count')
    op.drop_column('article', 'likes_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('article', sa.Column('views_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('article', sa.Column('comments_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('article', 'time_to_read')
    op.drop_column('article', 'rating')
    op.drop_column('article', 'number_of_ratings')
    # ### end Alembic commands ###
