"""get rid of entity fields

Revision ID: bb4486427f92
Revises: b16735932d51
Create Date: 2025-02-28 01:40:51.894253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb4486427f92'
down_revision = 'b16735932d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'string_field')
    op.drop_column('entities', 'enum_field')
    op.drop_column('entities', 'bool_field')
    op.drop_column('entities', 'int_field')
    op.drop_column('entities', 'string_array_field')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('string_array_field', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('entities', sa.Column('int_field', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('entities', sa.Column('bool_field', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('entities', sa.Column('enum_field', postgresql.ENUM('A', 'B', 'C', 'D', name='enum'), autoincrement=False, nullable=False))
    op.add_column('entities', sa.Column('string_field', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
