"""add user notifs field

Revision ID: f6d15863f300
Revises: 1cdcb12f69e0
Create Date: 2025-01-28 23:13:57.243414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d15863f300'
down_revision = '1cdcb12f69e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('allow_notifs', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'allow_notifs')
    # ### end Alembic commands ###
